const list = [
    {
      id: 1,
      title: "Atomic Habits",
      author: "by James Clear | 16 October 2018",
      price: 13.99,
      img: "https://m.media-amazon.com/images/I/81F90H7hnML._SY522_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "The Psychology of Money",
      author: "by Morgan Housel | 15 July 2021",
      price: 10.99,
      img: "https://m.media-amazon.com/images/I/715ucF1cMZS._SY522_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Rich Dad Poor Dad",
      author: "by Robert T. Kiyosaki | 1 January 2022",
      price: 12.99,
      img: "https://m.media-amazon.com/images/I/81BE7eeKzAL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Mindset",
      author: "by Carol Dweck | 2 February 2012",
      price: 17,
      img: "https://m.media-amazon.com/images/I/61FXPFVKD6L._SY522_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "The Four Agreements",
      author: "by Don Miguel Ruiz | 1 January 2023",
      price: 12.95,
      img: "https://m.media-amazon.com/images/I/91AfEwKjDgL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "THE 48 LAWS OF POWER",
      author: "by Robert Greene | 20 November 2000",
      price: 26,
      img: "https://m.media-amazon.com/images/I/61J3Uu4jOLL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "The Subtle Art of Not Giving A F*ck",
      author: "by Mark Manson | 19 January 2017",
      price: 16.99,
      img: "https://m.media-amazon.com/images/I/71t4GuxLCuL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Deep Work",
      author: "by Cal Newport | 1 January 2016",
      price: 11.99,
      img: "https://m.media-amazon.com/images/I/61TkOFwquPL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "The 5 Am Club",
      author: "by Robin Sharma | 19 December 2018",
      price: 15.99,
      img: "https://m.media-amazon.com/images/I/61ynLa0yRQL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Ikigai: Japanese secret to long and happy life",
      author: "by Francesc Miralles | 27 September 2017",
      price: 24,
      img: "https://m.media-amazon.com/images/I/81l3rZK4lnL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "How to Talk to Anyone",
      author: "by Leil lowndes | 1 January 2024",
      price: 20,
      img: "https://m.media-amazon.com/images/I/61+Cc-VuMmL._SY522_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Magic of Thinking Big",
      author: "by Schwartz David J  | 1 January 2016",
      price: 14.99,
      img: "https://m.media-amazon.com/images/I/81UZJqFG7VL._SY522_.jpg",
      amount: 1,
    },
];
  
export default list;